server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.137.200
      port: 8500
      discovery:
        hostname: 192.168.137.166
        service-name: ${spring.application.name}