server:
  port: 9004
spring:
  application:
    name: nacos-ribbon-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.200:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'