server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment-service_route
          uri: http://localhost:8001
          predicates:
            - Path=/payment/**