
server:
  port: 8001
spring:
  application:
    name: payment8001
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://192.168.137.131:32016/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
