server:
  port: 84
spring:
  application:
    name: nacos-ribbon-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.200:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        # 默认8719端口，加入被占用，端口会自动+1
        port: 8719
# 消费者将要去访问的微服务名称(注册进nacos的微服务提供者
service-url:
  nacos-user-service: http://nacos-ribbon-provider
# Feign开启sentinel支持
feign:
  sentinel:
    enabled: true